const pdf=require("pdf-parse");
const UA="MRI-Safety-Resolver/0.6";
const BGUIDE="https://www.bostonscientific.com/content/dam/elabeling/crm/51435609-001_IMAGEREADY_BRADY_MRITG_en_S.pdf";
const BLOOK="https://www.bostonscientific.com/imageready/en-US/model-lookup.html";
const EGUIDE="https://www.accessdata.fda.gov/cdrh_docs/pdf20/P200036D.pdf";
const EPMA="https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpma/pma.cfm?id=P200036";
const BMODELS=new Set(["J065","J066","J067","J175","J176","J177","J275","J276","J277","J279","L110","L111","L131","L210","L211","L231","L310","L311","L331","U128","U228"]);
const portals=[
[/boston scientific|guidant/i,"Boston Scientific",BLOOK],
[/medtronic/i,"Medtronic","https://manuals.medtronic.com/manuals/mri/en_US/home"],
[/abbott|st\.? jude/i,"Abbott","https://www.cardiovascular.abbott/us/en/hcp/mri-safety.html"],
[/biotronik/i,"BIOTRONIK","https://www.biotronik.com/en-us/professionals/featured-technologies/promri"]
];
const allowed=[/(^|\.)accessdata\.fda\.gov$/i,/(^|\.)bostonscientific\.com$/i,/(^|\.)medtronic\.com$/i,/(^|\.)manuals\.medtronic\.com$/i,/(^|\.)cardiovascular\.abbott$/i,/(^|\.)abbott\.com$/i,/(^|\.)biotronik\.com$/i];
const clean=s=>String(s||"").replace(/\s+/g," ").trim();
const mr=s=>{s=String(s||"").toLowerCase();return s.includes("conditional")?"MR Conditional":s.includes("unsafe")?"MR Unsafe":s.includes("safe")?"MR Safe":null};
const models=q=>[...new Set((String(q||"").toUpperCase().match(/\b[A-Z]{1,5}-?\d{2,8}[A-Z0-9-]*\b/g)||[]))];
async function text(url){const r=await fetch(url,{headers:{"User-Agent":UA},redirect:"follow"});if(!r.ok)throw Error(`Source ${r.status}`);const t=(r.headers.get("content-type")||"").toLowerCase();if(t.includes("pdf")||url.endsWith(".pdf"))return clean((await pdf(Buffer.from(await r.arrayBuffer()))).text);return clean((await r.text()).replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<[^>]+>/gi," "))}
async function fda(q,ms){let out=[],seen=new Set(),terms=ms.map(x=>["version_or_model_number",x,100]);terms.push(["brand_name",q,30],["device_description",q,20]);for(const [f,v,w] of terms.slice(0,5)){try{let u=new URL("https://api.fda.gov/device/udi.json");u.searchParams.set("search",`${f}:"${String(v).replace(/"/g,"")}"`);u.searchParams.set("limit","12");let r=await fetch(u);if(!r.ok)continue;for(const x of (await r.json()).results||[]){let id=x.record_key||JSON.stringify(x.identifiers||[]);if(seen.has(id))continue;seen.add(id);let m=clean(x.version_or_model_number),score=w+(ms.includes(m.toUpperCase())?150:0);out.push({score,brand:clean(x.brand_name)||clean(x.device_description)||"Unknown device",manufacturer:clean(x.company_name)||"Unknown manufacturer",model:m||null,mriSafety:clean(x.mri_safety)||null})}}catch(e){}}return out.sort((a,b)=>b.score-a.score).slice(0,10)}
function boston(t,m){const ok=x=>x.test(t);return {mrStatus:"MR Conditional",extraction:"PRIMARY SOURCE PARSED",systemRule:"The complete pulse-generator + lead system must be a valid ImageReady MR Conditional combination; generator model alone is not sufficient.",conditions:[
["Field strength","1.5 T or 3.0 T",ok(/1\.5 T.*3 T|1\.5 T or 3 T/i)],["Scanner","Horizontal-field, 1H proton, closed-bore",ok(/closed bore/i)],["Spatial gradient","≤ 50 T/m (5,000 G/cm)",ok(/50 T\/m|5,000 G\/cm/i)],["SAR","Whole body ≤ 2.0 W/kg; head ≤ 3.2 W/kg in Normal Operating Mode",ok(/2\.0 W\/kg|2\.0 watts\/kilogram/i)],["Slew rate","≤ 200 T/m/s per axis",ok(/200 T\/m\/s/i)],["MRI Protection Mode","Required during scan",ok(/MRI Protection Mode/i)],["Implant location","Left or right pectoral region",ok(/left or right pectoral/i)],["Waiting period","≥ 6 weeks after implant and/or lead revision/surgical modification",ok(/six \(6\) weeks|six weeks/i)],["Other components","No other active or abandoned implanted devices/components/accessories",ok(/No other active or abandoned implanted devices/i)],["System integrity","No fractured lead or compromised generator-lead integrity",ok(/No evidence of a fractured lead/i)],["Patient position","Supine or prone only",ok(/supine or prone/i)],["Monitoring","Pulse oximetry and/or ECG; backup therapy available",ok(/pulse oximetry.*electrocardiography|electrocardiography.*pulse oximetry/i)]
].map(x=>({key:x[0],value:x[1],sourceVerified:x[2]})),hardStops:["Exact lead model(s) not confirmed as a valid ImageReady combination","MRI Protection Mode unavailable/expired","<6 weeks after implant or lead revision","Active/abandoned implanted cardiac components present","Fractured lead or compromised system integrity","Scanner/sequence exceeds manufacturer limits"]}}
function ecoin(t){const ok=x=>x.test(t);return {mrStatus:"MR Conditional",extraction:"PRIMARY SOURCE PARSED",systemRule:"Use exact eCoin Model UUI labeling; implant must remain outside the bore under the stated distance/position rules.",conditions:[
["Field strength","1.5 T or 3.0 T",ok(/1\.5 T.*3 T|1\.5T.*3T/i)],["Implant distance","≥20 cm (7.9 in) from edge of scanner bore",ok(/20 cm|7\.9 in/i)],["Implanted lower leg","Must not enter MRI machine/bore",ok(/lower leg/i)&&ok(/MRI machine|bore/i)],["Patient Controller","MR Unsafe; keep magnet out of MRI room/facility",ok(/Patient Controller/i)&&ok(/MR Unsafe/i)],["RF heating","Not tested",ok(/RF heating/i)&&ok(/not tested/i)],["Image artifact","Not tested",ok(/artifact/i)&&ok(/not tested/i)],["Device OFF / MRI mode","No OFF or MRI-mode instruction detected in cited MRI section; verify current labeling",true]
].map(x=>({key:x[0],value:x[1],sourceVerified:x[2]})),hardStops:["Exact UUI model not confirmed","Field other than 1.5/3 T","Implant cannot remain ≥20 cm from bore edge","Implanted lower leg enters bore","Patient Controller magnet enters MRI environment"]}}
async function resolve(q){let ms=models(q),list=await fda(q,ms),best=list[0]||null,m=(best?.model||ms[0]||"").toUpperCase(),r;if(/ecoin/i.test(q)||m==="UUI"){r={resolver:"eCoin FDA labeling adapter",model:"UUI",guideUrl:EGUIDE,liveChecked:true,...ecoin(await text(EGUIDE))}}else if(/boston scientific|guidant/i.test(best?.manufacturer||q)&&BMODELS.has(m)){let live=await text(BGUIDE);r={resolver:"Boston Scientific ImageReady Brady adapter",model:m,guideUrl:BGUIDE,lookupUrl:BLOOK,liveChecked:true,...boston(live,m)}}else{let p=portals.find(x=>x[0].test(best?.manufacturer||q));r={resolver:p?`${p[1]} primary-source portal`:"General FDA/GUDID resolver",model:m||null,lookupUrl:p?.[2]||null,liveChecked:false,extraction:"SOURCE IDENTIFIED — CONDITIONS NOT YET PARSED",mrStatus:mr(best?.mriSafety),conditions:[],hardStops:["Do not infer full scan conditions from GUDID MR label alone","Open current manufacturer MRI IFU/manual for exact model and all components","Unresolved or conflicting source = human review"]}}let fs=mr(best?.mriSafety),ps=mr(r.mrStatus),ev=fs&&ps&&fs!==ps?{status:"CONFLICT FOUND",detail:`GUDID: ${fs}; primary source: ${ps}`} : ps?{status:"PRIMARY SOURCE RESULT",detail:ps}:fs?{status:"GUDID LABEL ONLY",detail:fs}:{status:"NOT VERIFIED",detail:"No authoritative MR classification resolved"};let links=[];if(r.guideUrl)links.push(["Primary MRI guide","Primary manufacturer/FDA",r.guideUrl]);if(r.lookupUrl)links.push(["Manufacturer lookup","Primary manufacturer",r.lookupUrl]);if(/ecoin/i.test(q)||m==="UUI")links.push(["FDA PMA P200036","Primary FDA",EPMA]);links.push(["AccessGUDID","Primary identification",`https://accessgudid.nlm.nih.gov/devices/search?query=${encodeURIComponent(m||q)}`],["FDA Recalls","Primary surveillance","https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfRES/RESSimpleSearch.cfm"],["FDA MAUDE","Signal reports only","https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfMAUDE/Search.cfm"],["MRIsafety.com","Secondary cross-reference","https://www.mrisafety.com/"]);return {checkedAt:new Date().toISOString(),extractedModels:ms,bestIdentity:best,candidates:list,evidenceStatus:ev,resolution:r,sourceLinks:links.map(x=>({label:x[0],authority:x[1],url:x[2]}))}}
function generic(t,m){let f=[],push=(k,re)=>{let x=t.match(re)?.[0];if(x)f.push({key:k,value:clean(x).slice(0,200)})};let s=mr(t);if(s)f.push({key:"MR classification",value:s});let fs=[...new Set(t.match(/\b(?:1\.5|3(?:\.0)?)\s*T(?:esla)?\b/gi)||[])];if(fs.length)f.push({key:"Field strengths mentioned",value:fs.slice(0,4).join(", ")});push("SAR",/(?:SAR|whole[- ]?body)[^.]{0,120}\d(?:\.\d+)?\s*W\/kg/i);push("B1+rms",/B1\+?rms[^.]{0,100}/i);push("Gradient",/(?:spatial gradient|gradient field)[^.]{0,120}(?:T\/m|G\/cm)/i);push("MRI mode/settings",/MRI (?:Protection|Ready|Settings|Mode)[^.]{0,120}/i);push("Coils",/(?:transmit\/receive|transmit-only|receive-only|RF coil)[^.]{0,140}/i);push("Monitoring",/(?:pulse oximetry|ECG|electrocardiography|monitor(?:ing)?)[^.]{0,120}/i);return {mrStatus:s,modelFound:m?new RegExp(`\\b${m.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\b`,"i").test(t):null,findings:f}}
module.exports=async(req,res)=>{res.setHeader("Cache-Control","no-store");if(req.method!=="POST")return res.status(405).json({error:"POST required"});try{if(req.body?.action==="source"){let u=String(req.body.url||"").trim(),m=String(req.body.model||"").trim();if(!allowed.some(x=>{try{return x.test(new URL(u).hostname)}catch(e){return false}}))return res.status(400).json({error:"Official FDA/manufacturer URL required"});return res.json({checkedAt:new Date().toISOString(),url:u,...generic(await text(u),m),warning:"Source-reading aid only; review complete current IFU/manual."})}let q=clean(req.body?.query);if(q.length<2)return res.status(400).json({error:"Enter device/model"});return res.json(await resolve(q))}catch(e){return res.status(502).json({error:e.message})}};